### ISSUE TITLE
在使用htmlunitdriver时报错

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/phoenix.webui.framework#33]
Exception in thread "main" org.openqa.selenium.WebDriverException: java.lang.IllegalArgumentException: Cannot locate declared field class or
g.apache.http.impl.client.HttpClientBuilder.dnsResolver
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:541)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:515)
	at glodon.jujian.test.HtmlUnitTest.main(HtmlUnitTest.java:21)
Caused by: java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.dnsResolver
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
	at org.apache.commons.lang3.reflect.FieldUtils.readDeclaredField(FieldUtils.java:471)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getField(HttpWebConnection.java:1096)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.createConnectionManager(HttpWebConnection.java:1019)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:177)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1364)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1281)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:383)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:305)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:452)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:526)
	... 2 more

**Comment by LinuxSuRen** [comment]
已修正
