### ISSUE TITLE
使用浏览器htmlUnit时报错

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/phoenix.webui.framework#39]
Exception in thread "main" java.lang.UnsupportedOperationException: Javascript is not enabled for this HtmlUnitDriver instance
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.getPageToInjectScriptInto(HtmlUnitDriver.java:716)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.executeScript(HtmlUnitDriver.java:665)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine.computeToolbarHeight(SeleniumEngine.java:854)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine$$FastClassBySpringCGLIB$$655932d8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine$$EnhancerBySpringCGLIB$$6c6b64fb.computeToolbarHeight(<generated>)
	at org.suren.autotest.web.framework.page.Page.open(Page.java:76)
	at sdfsf.OsChinaTest.main(OsChinaTest.java:22)

**Comment by LinuxSuRen** [comment]
已经添加默认支持js
